spring:
  application:
    name: device-hub
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:33064/dev_hub_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_passwd}
  flyway:
    user: ${DB_ADMIN_USERNAME:root}
    password: ${DB_ADMIN_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
